package apotheneum.jvyduna.patterns.chrome;

import java.util.List;
import java.util.Random;

import apotheneum.Apotheneum;
import apotheneum.ApotheneumPattern;
import apotheneum.jvyduna.util.AudioReactive;
import apotheneum.jvyduna.util.Ranges;
import apotheneum.jvyduna.util.SurfaceCanvas;
import apotheneum.jvyduna.util.TempoLock;
import heronarts.lx.LX;
import heronarts.lx.LXCategory;
import heronarts.lx.LXComponent;
import heronarts.lx.Tempo;
import heronarts.lx.color.LXColor;
import heronarts.lx.color.LXDynamicColor;
import heronarts.lx.parameter.CompoundParameter;
import heronarts.lx.parameter.DiscreteParameter;
import heronarts.lx.parameter.EnumParameter;
import heronarts.lx.parameter.TriggerParameter;

/**
 * A gothic CATHEDRAL grown from swells, for Oneohtrix Point Never's beatless
 * "Chrome Country" (the "acceptance / return to the father's faith" beat of the
 * Communicating arc). A self-similar arcade of pointed (lancet) arches wraps
 * the cube ring — one tall MAIN arch centered per wall, flanked by side arches
 * whose widths shrink by the golden ratio and whose peaks trace the same lancet
 * curve, so the whole face reads as a fractal of arches. The window tracery
 * inside every arch is GENERATED by an elementary (Wolfram) cellular automaton
 * rather than drawn cleanly, so the architecture reads subtly generated-wrong /
 * almost-corny from the start — the Lopatin uncanny hinge is the hero's DEFAULT
 * rendering mode, not a secondary effect.
 *
 * The structure GROWS from the floor as the Growth knob rises (Growth maps
 * directly to height, responding instantly); at full Growth the main arch tip
 * reaches the top row. Dissonance BENDS the image (hue-shift + a horizontal
 * tear-shear that then heals), resolution HEALS it (arches complete and glow —
 * the 1:43 HEAL/return callback), and the codex TearDown is a one-time,
 * time-lapse EROSION that crumbles the cathedral away and leaves a domed pile
 * of dust; Seed restores it. Drip coats the arch ridges with scintillating
 * energy that can build into upward beams of flowing light out of each arch
 * peak. Color runs cool/occult through the body and blooms warm-gold at the
 * finale via the Gold knob and the project palette (CA tracery reads from
 * palette swatch 2).
 *
 * See Cathedral.md (beside this file) for the full design note.
 */
@LXCategory("Apotheneum/jvyduna")
@LXComponent.Name("Cathedral")
@LXComponent.Description("A gothic cathedral of golden-ratio pointed arches whose window tracery is generated by a Wolfram cellular automaton: grown from the floor, bent by dissonance, healed at resolutions, dripping ridge-beams, and eroded to dust like a codex — cool/occult through the body, warm-gold at the finale")
public class Cathedral extends ApotheneumPattern {

  // ---- Geometry / arch constants (all CURATE: tune on hardware) ---------------

  /** Golden ratio: side arches shrink in width by this factor per step out. */
  private static final double PHI = 1.6180339887;

  /** Springline height (where the arch curve begins) as a fraction of the full
   *  grown height. Below it are the piers + window; above it the pointed curve. */
  private static final double SPRING_FRAC = 0.50; // CURATE

  /** Apex height of the MAIN (center) arch as a fraction of the surface height
   *  at full growth. 1.0 so the main tip reaches the top pixel row at Growth 1;
   *  side arches fall short via the master-curve height envelope. */
  private static final double APEX_FRAC = 1.0; // CURATE

  /** Faces the cube ring is divided into (one main arch centered per wall). */
  private static final int CUBE_FACES = 4;

  /** Bays the cylinder ring is divided into (one main arch centered per bay). */
  private static final int CYL_BAYS = 3; // CURATE

  /** Stone outline (rib) thickness under the arch curve, in rows. */
  private static final double RIB_ROWS = 2.0; // CURATE

  /** Floor plinth thickness, in rows. */
  private static final int BASE_ROWS = 2; // CURATE

  /** Arch-local |norm| beyond this (0 center .. 1 edge) is pier stone up to the
   *  springline. */
  private static final double PIER_NORM = 0.82; // CURATE

  /** Arch-local |norm| below this is the central window mullion bar. */
  private static final double MULLION_NORM = 0.06; // CURATE

  /** Pointed-arch shape exponent: 1.0 = triangular, <1 bulges toward a lancet.
   *  Used both for each arch and for the master peak-height envelope. */
  private static final double ARCH_EXP = 0.6; // CURATE

  /** Growth above which flying buttresses begin to appear (fully in at 1.0). */
  private static final double BUTTRESS_ONSET = 0.60; // CURATE

  // ---- Timing constants -------------------------------------------------------

  /** CA generation interval when free-running, Speed 0 -> 1 (ms). One row of
   *  tracery flows per step, so a full-height traversal is tens of seconds. */
  private static final double CA_STEP_AMBIENT_MS = 3500;
  private static final double CA_STEP_PEAK_MS = 1200;

  /** Bend (dissonance) glitch-pulse decay, and Heal glow decay (ms). */
  private static final double BEND_MS = 2200; // CURATE
  private static final double HEAL_MS = 3000; // CURATE

  /** Drip energy build/decay time constant (one-pole ease toward |Drip|). */
  private static final double DRIP_TAU = 450; // CURATE

  /** Fallback erosion period (ms) if the tempo division period is unavailable. */
  private static final double ERODE_FALLBACK_MS = 4000; // CURATE

  // ---- Glitch constants -------------------------------------------------------

  /** Peak hue rotation (degrees) at full effective glitch. */
  private static final double GLITCH_HUE_DEG = 90; // CURATE

  /** Peak horizontal tear-shear (columns) at full effective glitch. */
  private static final int MAX_SHEAR = 6; // CURATE

  // ---- Color constants --------------------------------------------------------

  // Fallbacks used when the palette swatch is empty. CURATE: picked blind.
  private static final float COOL_H = 255, COOL_S = 55, COOL_B = 62; // violet-indigo stone
  private static final float GOLD_H = 45,  GOLD_S = 85, GOLD_B = 100; // finale gold
  private static final float TRACE_H = 52, TRACE_S = 85, TRACE_B = 92; // swatch-2 fallback (amber)

  /** Full-Gold tracery target: a dimmer, half-brightness yellow (arches go
   *  brighter/deep-gold, tracery stays a softer yellow — the split). */
  private static final float YELLOW_H = 52, YELLOW_S = 90, YELLOW_B = 50; // CURATE

  /** Extra stone brightness boost at full Gold (arches brighter than tracery). */
  private static final double GOLD_STONE_BOOST = 0.35; // CURATE

  /** Window backing (dim stained-glass field behind the CA tracery). */
  private static final double WINDOW_BACK = 0.10; // CURATE

  /** Empty-valley starfield. */
  private static final double STAR_ONSET = 0.15; // CURATE
  private static final int NUM_STARS = 14; // CURATE
  private static final double STAR_MAX_B = 55; // CURATE

  // ---- Dust / erosion constants ----------------------------------------------

  /** Max dust-pile height in rows at the dome center. */
  private static final int DUST_MAX_ROWS = 6; // CURATE

  // ---- Curated CA rules (Top-10 notable elementary Wolfram rules) -------------

  /** The ten most notable/aesthetic elementary CA rules: chaos, Sierpinski,
   *  Turing-complex, class-4, additive-XOR, sparse fractals. */
  private static final int[] RULES = {30, 90, 110, 54, 60, 62, 102, 150, 126, 22};
  private static final String[] RULE_LABELS =
    {"R30", "R90", "R110", "R54", "R60", "R62", "R102", "R150", "R126", "R22"};

  // ---- Composition helpers ----------------------------------------------------

  private final AudioReactive audio;
  private final TempoLock tempoLock;
  private final Random random = new Random();

  // ---- Parameters (registration order is fixed; do not reorder) ---------------

  public final TriggerParameter seed =
    new TriggerParameter("Seed", this::seedTrigger)
    .setDescription("Re-seed the tracery cellular automaton with a fresh random row, and restore the cathedral if it has been eroded to dust");

  public final TriggerParameter bend =
    new TriggerParameter("Bend", this::bendTrigger)
    .setDescription("Dissonance bend: a hue-shift + tear-shear glitch pulse that then heals over ~2 s");

  public final TriggerParameter heal =
    new TriggerParameter("Heal", this::healTrigger)
    .setDescription("Resolution/return: snap the glitch to zero and flood the arches with a completing glow over ~3 s (the 1:43 HEAL callback)");

  public final TriggerParameter tearDown =
    new TriggerParameter("TearDown", this::tearDownTrigger)
    .setDescription("Codex teardown: a one-time, time-lapse erosion that crumbles the cathedral away and leaves a domed pile of dust (Seed restores)");

  public final TriggerParameter randomRule =
    new TriggerParameter("RandRule", this::randomRuleTrigger)
    .setDescription("Pick a new CA rule via a random walk that never revisits the last half of the available rules");

  public final CompoundParameter speed =
    new CompoundParameter("Speed", 0.35)
    .setDescription("CA advance speed: ambient (slow CA) to peak (faster CA)");

  public final CompoundParameter growth =
    new CompoundParameter("Growth", 0.4)
    .setDescription("Height: how tall/complete the arches are, grown from the floor; maps directly to height and responds instantly");

  public final DiscreteParameter rule =
    new DiscreteParameter("Rule", 1, 0, RULES.length)
    .setDescription("Which curated Wolfram elementary CA rule generates the window tracery")
    .setOptions(RULE_LABELS);

  public final CompoundParameter arches =
    new CompoundParameter("Arches", 3, 1, 7)
    .setDescription("Number of arches shown per face, centered on the main arch; odd counts are all whole, even counts add half-arches at the face edges (continuous)");

  public final CompoundParameter tracery =
    new CompoundParameter("Tracery", 0.6)
    .setDescription("Brightness of the CA-generated window tracery inside the arches");

  public final CompoundParameter glitch =
    new CompoundParameter("Glitch", 0)
    .setDescription("Dissonance amount: hue-shift + horizontal tear-shear of the whole image (Bend pulses this)");

  public final CompoundParameter gold =
    new CompoundParameter("Gold", 0)
    .setDescription("Cool/occult (0) to warm-gold (1). At full, the arches go brighter and deep-gold while the CA tracery goes toward a dimmer half-brightness yellow");

  public final CompoundParameter drip =
    new CompoundParameter("Drip", 0, -1, 1)
    .setDescription("Bidirectional ridge energy: negative drips a scintillating coating down the arch ribs; positive builds it upward into flowing beams out of each arch peak (up to 1x installation height, 1/4 arch width). Never touches the windows");

  public final CompoundParameter smooth =
    new CompoundParameter("Smooth", 1.0)
    .setDescription("Motion blending + antialiasing: 0 = steppy/posterized, 1 = smooth CA down-flow and antialiased arch edges");

  public final CompoundParameter audioDepth =
    new CompoundParameter("Audio", 0)
    .setDescription("Audio reactivity depth: 0 = pure screensaver (default), 1 = full reactivity");

  public final EnumParameter<Tempo.Division> tempoDiv =
    new EnumParameter<Tempo.Division>("TempoDiv", Tempo.Division.WHOLE)
    .setDescription("Tempo division over which a TearDown erosion completes");

  // ---- Surfaces / buffers (all preallocated; zero-alloc render) ---------------

  private final SurfaceCanvas ringCanvas =
    new SurfaceCanvas(Apotheneum.Cube.Ring.LENGTH, Apotheneum.GRID_HEIGHT);       // 200x45
  private final SurfaceCanvas ringWarp =
    new SurfaceCanvas(Apotheneum.Cube.Ring.LENGTH, Apotheneum.GRID_HEIGHT);
  private final SurfaceCanvas cylCanvas =
    new SurfaceCanvas(Apotheneum.Cylinder.Ring.LENGTH, Apotheneum.CYLINDER_HEIGHT); // 120x43
  private final SurfaceCanvas cylWarp =
    new SurfaceCanvas(Apotheneum.Cylinder.Ring.LENGTH, Apotheneum.CYLINDER_HEIGHT);

  /** Tracery CA histories: caHistory[row][col], row 0 = top; new generations
   *  are pushed at the top and flow downward. */
  private final byte[][] cubeCA =
    new byte[Apotheneum.GRID_HEIGHT][Apotheneum.Cube.Ring.LENGTH];
  private final byte[][] cylCA =
    new byte[Apotheneum.CYLINDER_HEIGHT][Apotheneum.Cylinder.Ring.LENGTH];

  /** Scratch: the CA's next top row, so the newest row crossfades in smoothly. */
  private final byte[] caIncoming = new byte[Apotheneum.Cube.Ring.LENGTH];

  // ---- Per-frame arch layout (recomputed per surface; preallocated) -----------

  private static final int MAX_W = Apotheneum.Cube.Ring.LENGTH;   // 200
  private final double[] colNorm = new double[MAX_W];       // 0 center .. 1 edge within arch
  private final double[] colApexShape = new double[MAX_W];  // master-curve height 0..1 at arch center
  private final double[] colTopH = new double[MAX_W];       // silhouette height per column (for drip)
  private final double[] boundR = new double[16];           // right-side arch boundaries in u-space

  private static final int MAX_PEAKS = 160;
  private int peakCount = 0;
  private final int[] peakX = new int[MAX_PEAKS];
  private final double[] peakHalfCols = new double[MAX_PEAKS];
  private final double[] peakApexShape = new double[MAX_PEAKS];

  // ---- Random-walk rule history (no-repeat over the last half of RULES) -------

  private final int[] recentRules = new int[RULES.length / 2];
  private int recentCount = 0;
  private int recentHead = 0;

  // ---- Animation state --------------------------------------------------------

  private double growthShown = 0;    // = Growth (instant, no easing)
  private double glitchPulse = 0;    // Bend envelope 0..1
  private double healGlow = 0;       // Heal envelope 0..1
  private double caAccumMs = 0;      // free-run CA timer
  private double caPhase = 0;        // fractional flow phase 0..1 within a CA step

  private double dripEnergy = 0;     // held/eased toward |Drip|
  private double dripTimeMs = 0;     // scintillation clock

  private boolean eroding = false;   // TearDown in progress
  private boolean destroyed = false; // eroded to dust; Seed restores
  private double tearPhase = 0;      // 0 = intact, 1 = fully eroded

  // Per-frame color cache (computed once in computeColors)
  private int stoneColor = 0xff000000;
  private int traceryColor = 0xff000000;
  private int windowBack = 0xff000000;
  private int dripColor = 0xff000000;
  private int dustColor = 0xff000000;
  private double glitchEff = 0;

  // Palette swatch cache (Satori-style): recomputed only when the swatch changes
  private int cachedSwatchHash = Integer.MIN_VALUE;
  private float baseCoolH = COOL_H, baseCoolS = COOL_S, baseCoolB = COOL_B;
  private float baseGoldH = GOLD_H, baseGoldS = GOLD_S, baseGoldB = GOLD_B;
  private float baseTraceH = TRACE_H, baseTraceS = TRACE_S, baseTraceB = TRACE_B;

  // Empty-valley starfield (normalized positions, slow twinkle)
  private final double[] starX = new double[NUM_STARS];
  private final double[] starY = new double[NUM_STARS];
  private final double[] starPhase = new double[NUM_STARS];
  private final double[] starSpeed = new double[NUM_STARS];
  private final double[] starHue = new double[NUM_STARS];
  private final double[] starDrift = new double[NUM_STARS];

  public Cathedral(LX lx) {
    super(lx);
    this.audio = new AudioReactive(lx).setDepth(this.audioDepth);
    this.tempoLock = new TempoLock(lx);

    addParameter("seed", this.seed);
    addParameter("bend", this.bend);
    addParameter("heal", this.heal);
    addParameter("tearDown", this.tearDown);
    addParameter("randomRule", this.randomRule);
    addParameter("speed", this.speed);
    addParameter("growth", this.growth);
    addParameter("rule", this.rule);
    addParameter("arches", this.arches);
    addParameter("tracery", this.tracery);
    addParameter("glitch", this.glitch);
    addParameter("gold", this.gold);
    addParameter("drip", this.drip);
    addParameter("smooth", this.smooth);
    addParameter("audio", this.audioDepth);
    addParameter("tempoDiv", this.tempoDiv);

    for (int i = 0; i < NUM_STARS; ++i) {
      this.starX[i] = this.random.nextDouble();
      this.starY[i] = this.random.nextDouble();
      this.starPhase[i] = this.random.nextDouble() * Math.PI * 2;
      this.starSpeed[i] = 0.0006 + this.random.nextDouble() * 0.0010; // rad/ms, slow
      this.starHue[i] = this.random.nextDouble() * 14;                // 0..14: reds
      this.starDrift[i] = (this.random.nextDouble() - 0.5) * 0.00002; // slow parallax
    }

    final int r0 = RULES[this.rule.getValuei()];
    seedCA(this.cubeCA, Apotheneum.Cube.Ring.LENGTH, r0, false);
    seedCA(this.cylCA, Apotheneum.Cylinder.Ring.LENGTH, r0, false);
  }

  // ---- Triggers ---------------------------------------------------------------

  /** Re-seed both CAs with a fresh RANDOM initial row, and RESTORE the cathedral
   *  if it has been eroded to dust — the windows regenerate and the arches grow
   *  back per the Growth knob. */
  private void seedTrigger() {
    final int r0 = RULES[this.rule.getValuei()];
    seedCA(this.cubeCA, Apotheneum.Cube.Ring.LENGTH, r0, true);
    seedCA(this.cylCA, Apotheneum.Cylinder.Ring.LENGTH, r0, true);
    this.destroyed = false;
    this.eroding = false;
    this.tearPhase = 0;
  }

  /** Dissonance bend: arm the glitch pulse (hue-shift + tear-shear). */
  private void bendTrigger() {
    this.glitchPulse = 1;
  }

  /** Resolution/return: clear the bend and flood a completing glow. */
  private void healTrigger() {
    this.glitchPulse = 0;
    this.healGlow = 1;
  }

  /** Codex teardown: begin the one-time erosion (ignored if already running or
   *  already reduced to dust). */
  private void tearDownTrigger() {
    if (!this.eroding && !this.destroyed) {
      this.eroding = true;
      this.tearPhase = 0;
    }
  }

  /** Random walk over the curated rules that never revisits the last
   *  RULES.length/2 chosen indices (nor the current one). */
  private void randomRuleTrigger() {
    final int n = RULES.length;
    final int cur = this.rule.getValuei();
    int pick = cur;
    for (int tries = 0; tries < 64; ++tries) {
      final int cand = this.random.nextInt(n);
      if (cand == cur) {
        continue;
      }
      boolean recent = false;
      for (int i = 0; i < this.recentCount; ++i) {
        if (this.recentRules[i] == cand) {
          recent = true;
          break;
        }
      }
      if (!recent) {
        pick = cand;
        break;
      }
    }
    if (this.recentRules.length > 0) {
      this.recentRules[this.recentHead] = pick;
      this.recentHead = (this.recentHead + 1) % this.recentRules.length;
      if (this.recentCount < this.recentRules.length) {
        ++this.recentCount;
      }
    }
    this.rule.setValue(pick);
  }

  // ---- Render -----------------------------------------------------------------

  @Override
  protected void render(double deltaMs) {
    this.audio.tick(deltaMs);
    setColors(LXColor.BLACK);

    this.growthShown = this.growth.getValue(); // instant: Growth == height
    updateEnvelopes(deltaMs);

    // CA free-runs on the speed-scaled timer; track a fractional flow phase so
    // the tracery slides down smoothly instead of snapping row-by-row.
    final double stepMs = Ranges.exp(this.speed.getValue(), CA_STEP_AMBIENT_MS, CA_STEP_PEAK_MS);
    this.caAccumMs += deltaMs;
    boolean stepNow = false;
    if (this.caAccumMs >= stepMs) {
      this.caAccumMs -= stepMs;
      stepNow = true;
    }
    if (this.audio.trebleHit()) {
      stepNow = true;
    }
    this.caPhase = clamp01(this.caAccumMs / Math.max(1, stepMs));
    if (stepNow) {
      final int r = RULES[this.rule.getValuei()];
      step(this.cubeCA, Apotheneum.Cube.Ring.LENGTH, r);
      step(this.cylCA, Apotheneum.Cylinder.Ring.LENGTH, r);
    }

    computeColors();

    final boolean warp = this.glitchEff > 0.01;

    // Cube ring: the four cathedral walls; interior = the nave
    this.ringCanvas.fill(LXColor.BLACK);
    if (!this.destroyed) {
      fillArches(this.ringCanvas, this.cubeCA, CUBE_FACES, this.eroding);
      drawButtresses(this.ringCanvas);
      drawDrip(this.ringCanvas);
    }
    if (this.eroding || this.destroyed) {
      drawDust(this.ringCanvas, this.destroyed ? 1.0 : this.tearPhase, CUBE_FACES);
    }
    if (!this.destroyed && !this.eroding && this.growthShown < STAR_ONSET) {
      drawStars(this.ringCanvas);
    }
    if (warp) {
      warpCopy(this.ringCanvas, this.ringWarp);
      this.ringWarp.copyTo(Apotheneum.cube.exterior, this.colors);
    } else {
      this.ringCanvas.copyTo(Apotheneum.cube.exterior, this.colors);
    }
    copyCubeExterior();

    // Cylinder: ambulatory arcade; interior copied
    this.cylCanvas.fill(LXColor.BLACK);
    if (!this.destroyed) {
      fillArches(this.cylCanvas, this.cylCA, CYL_BAYS, this.eroding);
      drawDrip(this.cylCanvas);
    }
    if (this.eroding || this.destroyed) {
      drawDust(this.cylCanvas, this.destroyed ? 1.0 : this.tearPhase, CYL_BAYS);
    }
    if (!this.destroyed && !this.eroding && this.growthShown < STAR_ONSET) {
      drawStars(this.cylCanvas);
    }
    if (warp) {
      warpCopy(this.cylCanvas, this.cylWarp);
      this.cylWarp.copyTo(Apotheneum.cylinder.exterior, this.colors);
    } else {
      this.cylCanvas.copyTo(Apotheneum.cylinder.exterior, this.colors);
    }
    copyCylinderExterior();
  }

  // ---- Envelopes --------------------------------------------------------------

  private void updateEnvelopes(double deltaMs) {
    this.glitchPulse = Math.max(0, this.glitchPulse - deltaMs / BEND_MS);
    this.healGlow = Math.max(0, this.healGlow - deltaMs / HEAL_MS);

    // Drip energy builds/holds toward |Drip| with a one-pole ease.
    final double dripTarget = Math.abs(this.drip.getValue());
    final double a = 1 - Math.exp(-deltaMs / DRIP_TAU);
    this.dripEnergy += (dripTarget - this.dripEnergy) * a;
    this.dripTimeMs += deltaMs;

    // TearDown erosion advances over one tempo-division period.
    if (this.eroding) {
      double per = this.tempoLock.divisionMs(this.tempoDiv.getEnum());
      if (!(per > 50)) {
        per = ERODE_FALLBACK_MS;
      }
      this.tearPhase += deltaMs / per;
      if (this.tearPhase >= 1) {
        this.tearPhase = 1;
        this.eroding = false;
        this.destroyed = true;
      }
    }

    for (int i = 0; i < NUM_STARS; ++i) {
      this.starPhase[i] += this.starSpeed[i] * deltaMs;
      this.starX[i] += this.starDrift[i] * deltaMs;
      this.starX[i] -= Math.floor(this.starX[i]);
    }
  }

  // ---- Color ------------------------------------------------------------------

  private void computeColors() {
    refreshPaletteCache();

    final double goldEff = clamp01(this.gold.getValue() + 0.5 * this.healGlow);
    final double glow = clamp01(0.30 + 0.55 * this.growthShown
      + 0.30 * this.audio.level + 0.5 * this.healGlow);
    this.glitchEff = clamp01(this.glitch.getValue() + this.glitchPulse);
    final double glitchHue = this.glitchEff * GLITCH_HUE_DEG;

    // Stone/arches: cool -> gold, and brighter at high Gold.
    final float sh = (float) (wrapLerpHue(this.baseCoolH, this.baseGoldH, goldEff) + glitchHue);
    final float ss = (float) lerp(this.baseCoolS, this.baseGoldS, goldEff);
    final double stoneBoost = 1.0 + GOLD_STONE_BOOST * goldEff;
    final float sb = (float) (lerp(this.baseCoolB, this.baseGoldB, goldEff) * glow * stoneBoost);
    this.stoneColor = LXColor.hsb(wrap360(sh), clampB(ss), clampB(sb));
    this.windowBack = LXColor.hsb(wrap360(sh), clampB(ss), clampB((float) (sb * WINDOW_BACK)));

    // Tracery (CA): base from swatch 2; toward a dimmer half-bright yellow at
    // full Gold, so it reads distinct from the brighter gold arches.
    final float th = (float) (wrapLerpHue(this.baseTraceH, YELLOW_H, goldEff) + glitchHue);
    final float ts = (float) lerp(this.baseTraceS, YELLOW_S, goldEff);
    final double tbBase = lerp(this.baseTraceB, YELLOW_B, goldEff);
    final double traceryB = tbBase * glow * (0.5 + 0.5 * this.tracery.getValue())
      * (1.0 + 0.4 * this.audio.treble);
    this.traceryColor = LXColor.hsb(wrap360(th), clampB(ts), clampB((float) traceryB));

    // Drip energy color: a bright version of the gold end.
    this.dripColor = LXColor.hsb(wrap360(this.baseGoldH), clampB(this.baseGoldS), 100);

    // Dust: a dim version of the stone.
    this.dustColor = scale(this.stoneColor, 0.5);
  }

  private void refreshPaletteCache() {
    final List<LXDynamicColor> swatch = this.lx.engine.palette.swatch.colors;
    final int n = swatch.size();
    int hash = n;
    if (n > 0) {
      hash = 31 * hash + swatch.get(0).getColor();
      hash = 31 * hash + swatch.get(n - 1).getColor();
      if (n > 1) {
        hash = 31 * hash + swatch.get(1).getColor();
      }
    }
    if (hash == this.cachedSwatchHash) {
      return;
    }
    this.cachedSwatchHash = hash;
    if (n == 0) {
      this.baseCoolH = COOL_H; this.baseCoolS = COOL_S; this.baseCoolB = COOL_B;
      this.baseGoldH = GOLD_H; this.baseGoldS = GOLD_S; this.baseGoldB = GOLD_B;
      this.baseTraceH = TRACE_H; this.baseTraceS = TRACE_S; this.baseTraceB = TRACE_B;
      return;
    }
    // Cool end = first swatch color; warm end = last; CA tracery = swatch 2.
    final int cool = swatch.get(0).getColor();
    final int goldC = swatch.get(n - 1).getColor();
    final int trace = (n > 1) ? swatch.get(1).getColor() : cool;
    this.baseCoolH = LXColor.h(cool); this.baseCoolS = LXColor.s(cool); this.baseCoolB = LXColor.b(cool);
    this.baseGoldH = LXColor.h(goldC); this.baseGoldS = LXColor.s(goldC); this.baseGoldB = LXColor.b(goldC);
    this.baseTraceH = LXColor.h(trace); this.baseTraceS = LXColor.s(trace); this.baseTraceB = LXColor.b(trace);
  }

  // ---- Arch layout ------------------------------------------------------------

  /** Compute, into the preallocated column/peak arrays, a per-face symmetric
   *  golden-ratio arcade: one main arch centered per face, side arches shrinking
   *  in width by PHI outward, and arch-peak heights tracing the same lancet
   *  curve (self-similar). N is the continuous count of arches shown per face. */
  private void computeArchLayout(int w, int faceCount, double N) {
    final int faceW = w / faceCount;
    final double halfFaceCols = faceW / 2.0;

    // Solve the main-arch width W0 (in half-face u-units, half-face = 1) so the
    // face edge falls at exactly m arches per side: m = (N-1)/2, with the outer
    // arch revealed fractionally for a pop-free whole<->half morph.
    double m = (N - 1) / 2.0;
    if (m < 0) {
      m = 0;
    }
    final int fm = (int) Math.floor(m);
    final double fr = m - fm;
    double s = 0.5;
    double pk = 1.0;
    for (int k = 1; k <= fm; ++k) {
      pk /= PHI;
      s += pk;
    }
    s += fr * (pk / PHI);
    final double w0 = 1.0 / s;

    // Right-side boundaries in u: b0 = W0/2, then += W0/PHI^k until past the edge.
    int nb = 0;
    double bb = w0 / 2.0;
    this.boundR[nb++] = bb;
    double wk = w0;
    while (bb < 1.0 && nb < this.boundR.length) {
      wk /= PHI;
      bb += wk;
      this.boundR[nb++] = bb;
    }

    // Per-column: find the arch and local normalized position.
    for (int x = 0; x < w; ++x) {
      final int localCol = x % faceW;
      final double u = ((localCol + 0.5) / faceW) * 2.0 - 1.0;
      final double au = Math.abs(u);
      double lo = 0, hi = this.boundR[0];
      int idx = 0;
      while (idx + 1 < nb && au >= hi) {
        lo = hi;
        hi = this.boundR[++idx];
      }
      double norm, centerU;
      if (idx == 0) {
        centerU = 0;                                  // main arch folds at u=0
        norm = au / Math.max(1e-6, this.boundR[0]);
      } else {
        centerU = (lo + hi) / 2.0;
        norm = Math.abs(au - centerU) / Math.max(1e-6, (hi - lo) / 2.0);
      }
      this.colNorm[x] = clamp01(norm);
      this.colApexShape[x] = Math.pow(Math.max(0, 1 - centerU), ARCH_EXP);
    }

    // Peaks (arch centers within the face) for the drip beams.
    this.peakCount = 0;
    for (int f = 0; f < faceCount; ++f) {
      final double faceCenterCol = f * faceW + halfFaceCols;
      addPeak((int) Math.round(faceCenterCol), this.boundR[0] * halfFaceCols, 1.0);
      double lo = this.boundR[0];
      for (int k = 1; k < nb; ++k) {
        final double hi = this.boundR[k];
        final double cU = (lo + hi) / 2.0;
        if (cU <= 1.0 + 1e-6) {
          final double halfCols = (hi - lo) / 2.0 * halfFaceCols;
          final double apexShape = Math.pow(Math.max(0, 1 - cU), ARCH_EXP);
          final double off = cU * halfFaceCols;
          addPeak((int) Math.round(faceCenterCol + off), halfCols, apexShape);
          addPeak((int) Math.round(faceCenterCol - off), halfCols, apexShape);
        }
        lo = hi;
      }
    }
  }

  private void addPeak(int x, double halfCols, double apexShape) {
    if (this.peakCount >= MAX_PEAKS) {
      return;
    }
    this.peakX[this.peakCount] = x;
    this.peakHalfCols[this.peakCount] = halfCols;
    this.peakApexShape[this.peakCount] = apexShape;
    ++this.peakCount;
  }

  // ---- Arch rendering ---------------------------------------------------------

  private void fillArches(SurfaceCanvas c, byte[][] ca, int faceCount, boolean erode) {
    final int w = c.width;
    final int h = c.height;
    final double g = this.growthShown;
    if (g <= 0.001) {
      return; // nothing grown yet (valley); stars handle the field
    }
    computeArchLayout(w, faceCount, this.arches.getValue());
    final int ruleNum = RULES[this.rule.getValuei()];
    evolve(ca[0], this.caIncoming, w, ruleNum); // next top row, for smooth in-flow

    final double springH = g * SPRING_FRAC * (h - 1);
    final double fullApex = g * APEX_FRAC * (h - 1);
    final double sm = this.smooth.getValue();
    final double cph = this.caPhase;
    final double tp = this.tearPhase;

    for (int x = 0; x < w; ++x) {
      final double norm = this.colNorm[x];
      final double archApex = springH + (fullApex - springH) * this.colApexShape[x];
      final double shape = Math.pow(Math.max(0, 1 - norm), ARCH_EXP);
      final double topH = springH + (archApex - springH) * shape;
      this.colTopH[x] = topH;

      for (int y = 0; y < h; ++y) {
        final double hb = (h - 1) - y;             // height from the floor
        if (hb < 0 || hb > topH + 0.5) {
          continue;                                 // outside the silhouette
        }
        if (erode && eroded(x, hb, h, tp)) {
          continue;                                 // crumbled away
        }
        // Antialiased silhouette edge (softened by Smooth)
        final double edgeCover = clamp01((topH - hb) + 0.5);
        final double cover = 1 - sm * (1 - edgeCover);

        final boolean pier = (norm > PIER_NORM) && (hb <= springH);
        final boolean mullion = (norm < MULLION_NORM) && (hb <= springH);
        final boolean base = hb < BASE_ROWS;
        final boolean outline = (topH - hb) < RIB_ROWS;
        int col;
        if (pier || mullion || base || outline) {
          col = this.stoneColor;
        } else {
          // CA tracery, vertically interpolated toward the row above so it flows
          // down smoothly rather than stepping (scaled by Smooth).
          final double cell = (y == 0)
            ? lerp(ca[0][x], this.caIncoming[x], cph * sm)
            : lerp(ca[y][x], ca[y - 1][x], cph * sm);
          col = LXColor.lerp(this.windowBack, this.traceryColor, (float) clamp01(cell));
        }
        c.set(x, y, scale(col, cover));
      }
    }
  }

  /** Rising-threshold erosion: higher pixels crumble first (collapse downward),
   *  jittered per pixel. True once tearPhase passes the pixel's erode time. */
  private static boolean eroded(int x, double hb, int h, double tearPhase) {
    final double nh = hb / Math.max(1, (h - 1));      // 0 floor .. 1 top
    final double erodeTime = (1 - nh) * 0.75 + hash2(x, (int) Math.round(hb)) * 0.25;
    return tearPhase > erodeTime;
  }

  /** Flying buttresses: short diagonal stone struts leaning off each arch's pier
   *  edges, fading in as growth passes BUTTRESS_ONSET. Cube ring only (called
   *  after fillArches so the peak arrays are current). */
  private void drawButtresses(SurfaceCanvas c) {
    final double g = this.growthShown;
    if (g < BUTTRESS_ONSET) {
      return;
    }
    final double bf = clamp01((g - BUTTRESS_ONSET) / (1 - BUTTRESS_ONSET));
    final int h = c.height;
    final int strutColor = scale(this.stoneColor, 0.65 + 0.35 * bf);
    final int springY = (int) Math.round((h - 1) - g * SPRING_FRAC * (h - 1));
    final int dx = (int) Math.round(6 * bf);       // CURATE: strut reach
    final int drop = (int) Math.round(8 * bf);     // CURATE: strut drop
    if (dx <= 0 || drop <= 0) {
      return;
    }
    for (int p = 0; p < this.peakCount; ++p) {
      final int hw = (int) Math.round(this.peakHalfCols[p]);
      final int lft = this.peakX[p] - hw;
      final int rgt = this.peakX[p] + hw;
      c.line(lft, springY, lft - dx, Math.min(h - 1, springY + drop), strutColor);
      c.line(rgt, springY, rgt + dx, Math.min(h - 1, springY + drop), strutColor);
    }
  }

  // ---- Drip (ridge energy -> upward beams) ------------------------------------

  /** Coat the arch ridges with scintillating energy (never the windows), and —
   *  when Drip is positive — build that energy upward into flowing beams out of
   *  each arch peak. Uses colTopH/peaks from the preceding fillArches. */
  private void drawDrip(SurfaceCanvas c) {
    final double e = this.dripEnergy;
    if (e < 0.02) {
      return;
    }
    final int w = c.width;
    final int h = c.height;
    final double g = this.growthShown;
    if (g <= 0.001) {
      return;
    }
    final double springH = g * SPRING_FRAC * (h - 1);
    final double fullApex = g * APEX_FRAC * (h - 1);
    final double dir = Math.signum(this.drip.getValue());
    final double t = this.dripTimeMs;

    // Ridge coating on every column's outline pixel (scintillation flows down for
    // negative Drip, up for positive).
    final double flow = (dir < 0) ? 1 : -1;
    for (int x = 0; x < w; ++x) {
      final int ridgeY = (int) Math.round((h - 1) - this.colTopH[x]);
      final double scint = 0.5 + 0.5 * Math.sin(t * 0.006 * flow + x * 0.5);
      final double bri = e * (0.35 + 0.35 * scint);
      c.setMax(x, ridgeY, scale(this.dripColor, bri));
    }

    // Upward beams out of each arch peak (positive Drip).
    if (dir >= 0) {
      final int beamLen = (int) Math.round(e * (h - 1)); // up to 1x installation height
      for (int p = 0; p < this.peakCount; ++p) {
        final int cx = this.peakX[p];
        final double archApex = springH + (fullApex - springH) * this.peakApexShape[p];
        final int peakY = (int) Math.round((h - 1) - archApex);
        final double beamHalfMax = 0.25 * this.peakHalfCols[p]; // ~1/4 arch width
        for (int j = 0; j <= beamLen; ++j) {
          final int yy = peakY - j;
          if (yy < 0) {
            break;
          }
          final double taper = 1 - (double) j / Math.max(1, beamLen);
          final double scint = 0.5 + 0.5 * Math.sin(t * 0.01 - j * 0.6 + cx * 0.3);
          final double bri = e * taper * (0.5 + 0.5 * scint);
          final int wc = (int) Math.round(beamHalfMax * taper);
          for (int dxp = -wc; dxp <= wc; ++dxp) {
            final double wf = 1 - Math.abs(dxp) / (double) (wc + 1);
            c.setMax(cx + dxp, yy, scale(this.dripColor, bri * wf));
          }
        }
      }
    }
  }

  // ---- Dust (post-erosion) ----------------------------------------------------

  /** Domed piles of dust along the floor: every-other-pixel checkerboard, a
   *  cosine dome per face, dim stone color. level 0..1 = pile height fraction. */
  private void drawDust(SurfaceCanvas c, double level, int faceCount) {
    if (level <= 0.001) {
      return;
    }
    final int w = c.width;
    final int h = c.height;
    final int faceW = w / faceCount;
    for (int x = 0; x < w; ++x) {
      final double lu = (x % faceW) / (double) faceW;
      final double dome = Math.sin(Math.PI * lu);   // 0 at face edges, 1 center
      final int pileH = (int) Math.round(level * DUST_MAX_ROWS * (0.35 + 0.65 * dome));
      for (int j = 0; j < pileH; ++j) {
        final int y = (h - 1) - j;
        if (y < 0) {
          break;
        }
        if (((x + y) & 1) == 0) {                   // every other pixel on
          c.set(x, y, this.dustColor);
        }
      }
    }
  }

  // ---- Empty-valley starfield -------------------------------------------------

  private void drawStars(SurfaceCanvas c) {
    final double alpha = clamp01((STAR_ONSET - this.growthShown) / STAR_ONSET);
    if (alpha <= 0.01) {
      return;
    }
    final int w = c.width;
    final int h = c.height;
    for (int i = 0; i < NUM_STARS; ++i) {
      final double tw = 0.4 + 0.6 * (0.5 + 0.5 * Math.sin(this.starPhase[i]));
      final float b = clampB((float) (STAR_MAX_B * alpha * tw));
      if (b < 1) {
        continue;
      }
      final int x = (int) Math.floor(this.starX[i] * w);
      final int y = (int) Math.floor(this.starY[i] * h);
      c.setMax(x, y, LXColor.hsb((float) this.starHue[i], 85, b));
    }
  }

  // ---- Glitch warp ------------------------------------------------------------

  /** Copy src -> dst applying the dissonance tear-shear (per-row horizontal
   *  offset). Identity when the glitch is inactive. x wraps (ring topology). */
  private void warpCopy(SurfaceCanvas src, SurfaceCanvas dst) {
    final int w = src.width;
    final int h = src.height;
    final double gEff = this.glitchEff;
    for (int y = 0; y < h; ++y) {
      final int shear = (int) Math.round(shearNoise(y) * MAX_SHEAR * gEff);
      for (int x = 0; x < w; ++x) {
        dst.set(x, y, src.get(x + shear, y));       // get() wraps x
      }
    }
  }

  /** Cheap deterministic per-row shear noise in [-1, 1]. */
  private static double shearNoise(int y) {
    double n = Math.sin(y * 12.9898) * 43758.5453;
    n -= Math.floor(n);
    return n * 2 - 1;
  }

  /** Cheap deterministic 2D hash in [0, 1). */
  private static double hash2(int x, int y) {
    double n = Math.sin(x * 12.9898 + y * 78.233) * 43758.5453;
    return n - Math.floor(n);
  }

  // ---- Cellular automaton -----------------------------------------------------

  /** Seed a CA history: top row from a single center cell (or a random sparse
   *  row) then generate downward to fill the window. */
  private void seedCA(byte[][] hist, int w, int rule, boolean randomize) {
    final byte[] top = hist[0];
    java.util.Arrays.fill(top, (byte) 0);
    if (randomize) {
      for (int i = 0; i < w; ++i) {
        top[i] = (byte) (this.random.nextInt(4) == 0 ? 1 : 0); // ~25% density
      }
    } else {
      top[w / 2] = 1;
    }
    for (int r = 1; r < hist.length; ++r) {
      evolve(hist[r - 1], hist[r], w, rule);
    }
  }

  /** Advance the CA one generation: push a new top row (evolved from the old
   *  top) and flow the rest downward. Zero-alloc (pointer rotation). */
  private static void step(byte[][] hist, int w, int rule) {
    final byte[] recycled = hist[hist.length - 1];
    for (int r = hist.length - 1; r >= 1; --r) {
      hist[r] = hist[r - 1];
    }
    hist[0] = recycled;
    evolve(hist[1], hist[0], w, rule);
  }

  /** Elementary CA update: out[i] = bit (3-neighborhood -> rule). Wraps (ring).*/
  private static void evolve(byte[] in, byte[] out, int w, int rule) {
    for (int i = 0; i < w; ++i) {
      final int l = in[(i - 1 + w) % w];
      final int cc = in[i];
      final int r = in[(i + 1) % w];
      final int idx = (l << 2) | (cc << 1) | r;
      out[i] = (byte) ((rule >> idx) & 1);
    }
  }

  // ---- Small math helpers -----------------------------------------------------

  private static double clamp01(double v) {
    return (v < 0) ? 0 : (v > 1) ? 1 : v;
  }

  private static float clampB(float v) {
    return (v < 0) ? 0 : (v > 100) ? 100 : v;
  }

  private static double lerp(double a, double b, double t) {
    return a + (b - a) * t;
  }

  /** Shortest-path hue interpolation in degrees (wraps around the color wheel).*/
  private static double wrapLerpHue(double a, double b, double t) {
    double d = b - a;
    d -= 360 * Math.floor((d + 180) / 360);
    return a + d * t;
  }

  private static float wrap360(float h) {
    h -= 360f * (float) Math.floor(h / 360f);
    return h;
  }

  private static int scale(int argb, double m) {
    if (m <= 0) {
      return 0xff000000;
    }
    if (m > 1) {
      m = 1;
    }
    final int r = (int) (((argb >> 16) & 0xff) * m);
    final int g = (int) (((argb >> 8) & 0xff) * m);
    final int b = (int) ((argb & 0xff) * m);
    return 0xff000000 | (r << 16) | (g << 8) | b;
  }
}
