package apotheneum.jvyduna.patterns.chrome;

import java.util.List;
import java.util.Random;

import apotheneum.Apotheneum;
import apotheneum.ApotheneumPattern;
import apotheneum.jvyduna.util.AudioReactive;
import apotheneum.jvyduna.util.Ranges;
import apotheneum.jvyduna.util.SurfaceCanvas;
import apotheneum.jvyduna.util.TempoLock;
import apotheneum.jvyduna.util.TriggerBag;
import heronarts.lx.LX;
import heronarts.lx.LXCategory;
import heronarts.lx.LXComponent;
import heronarts.lx.Tempo;
import heronarts.lx.color.LXColor;
import heronarts.lx.color.LXDynamicColor;
import heronarts.lx.parameter.BooleanParameter;
import heronarts.lx.parameter.CompoundParameter;
import heronarts.lx.parameter.DiscreteParameter;
import heronarts.lx.parameter.EnumParameter;
import heronarts.lx.parameter.TriggerParameter;

/**
 * A gothic CATHEDRAL grown from swells, for Oneohtrix Point Never's beatless
 * "Chrome Country" (the "acceptance / return to the father's faith" beat of the
 * Communicating arc). A continuous arcade of pointed (lancet) arches wraps the
 * cube ring — the four buttressed walls — with the cube interior read as the
 * enclosing nave; the cylinder mirrors the arcade as an ambulatory. The window
 * tracery inside every arch is GENERATED by an elementary (Wolfram) cellular
 * automaton rather than drawn cleanly, so the architecture reads subtly
 * generated-wrong / almost-corny from the start — the Lopatin uncanny hinge is
 * the hero's DEFAULT rendering mode, not a secondary effect.
 *
 * The structure GROWS from the floor as the Growth knob rises (envelope-driven
 * by the arrange composition, since the track is beatless — no TempoLock in the
 * body); a full raise of the nave takes >= 5 s. Dissonance BENDS the image
 * (hue-shift + a horizontal tear-shear that then heals), resolution HEALS it
 * (arches complete and glow — the 1:43 HEAL/return callback), and the codex
 * TearDown rotates vertical slices toward their page-edges and back, as if the
 * cathedral were a book being closed. When the structure recedes to almost
 * nothing (the 3:20-4:00 valley) a sparse field of slow, cold, red-shifted
 * stars holds the darkness. Color runs cool/occult through the body and blooms
 * warm-gold at the finale via the Warmth knob and the project palette.
 *
 * See Cathedral.md (beside this file) for the full design note.
 */
@LXCategory("Apotheneum/jvyduna")
@LXComponent.Name("Cathedral")
@LXComponent.Description("A gothic cathedral of pointed arches whose window tracery is generated by a Wolfram cellular automaton: grown from envelope swells, bent by dissonance, healed at resolutions, and torn down like a codex — cool/occult through the body, warm-gold at the finale")
public class Cathedral extends ApotheneumPattern {

  // ---- Geometry / arch constants (all CURATE: tune on hardware) ---------------

  /** Springline height (where the arch curve begins) as a fraction of the full
   *  grown height. Below it are the piers + window; above it the pointed curve. */
  private static final double SPRING_FRAC = 0.50; // CURATE

  /** Apex height as a fraction of the surface height at full growth (leaves a
   *  little dark headroom above the arches). */
  private static final double APEX_FRAC = 0.92; // CURATE

  /** Reference wall width the arch count is quoted against (one cube face). The
   *  arcade is retiled to a whole number of arches around each full ring so it
   *  wraps seamlessly. */
  private static final double REF_WALL_COLS = Apotheneum.GRID_WIDTH; // 50

  /** Stone outline (rib) thickness under the arch curve, in rows. */
  private static final double RIB_ROWS = 2.0; // CURATE

  /** Floor plinth thickness, in rows. */
  private static final int BASE_ROWS = 2; // CURATE

  /** Columns with |offset-from-arch-center| beyond this (normalized 0..1) are
   *  pier stone up to the springline. */
  private static final double PIER_NORM = 0.82; // CURATE

  /** Half-width of the central window mullion bar, in arch-local fraction. */
  private static final double MULLION_HALF = 0.03; // CURATE

  /** Pointed-arch shape exponent: 1.0 = triangular, <1 bulges toward a lancet. */
  private static final double ARCH_EXP = 0.6; // CURATE

  /** Growth above which flying buttresses begin to appear (fully in at 1.0). */
  private static final double BUTTRESS_ONSET = 0.60; // CURATE

  // ---- Timing constants -------------------------------------------------------

  /** Growth ease time for a full 0->1 raise of the nave, at energy 0 and 1.
   *  Both >= the 5 s sustained-motion cap. */
  private static final double GROWTH_SECONDS_AMBIENT = 8.0;
  private static final double GROWTH_SECONDS_PEAK = 5.0;

  /** CA generation interval when free-running (Sync off), energy 0 -> 1 (ms).
   *  One row of tracery flows per step, so a full-height traversal is >= 45x
   *  this — tens of seconds, far above the sustained cap. */
  private static final double CA_STEP_AMBIENT_MS = 3500;
  private static final double CA_STEP_PEAK_MS = 1200;

  /** Bend (dissonance) glitch-pulse decay, and Heal glow decay (ms). Both are
   *  event-like envelopes, > the 1.5 s event minimum. */
  private static final double BEND_MS = 2200; // CURATE
  private static final double HEAL_MS = 3000; // CURATE

  /** Codex TearDown: rise (rotate slices toward page-edges), hold, then fall
   *  (rebuild), in ms. Each leg > the 1.5 s event minimum. */
  private static final double TEAR_RISE_MS = 3500; // CURATE
  private static final double TEAR_HOLD_MS = 900;  // CURATE
  private static final double TEAR_FALL_MS = 3500; // CURATE

  // ---- Glitch / warp constants ------------------------------------------------

  /** Peak hue rotation (degrees) at full effective glitch. */
  private static final double GLITCH_HUE_DEG = 90; // CURATE

  /** Peak horizontal tear-shear (columns) at full effective glitch. */
  private static final int MAX_SHEAR = 6; // CURATE

  /** Number of vertical slices the codex teardown folds. */
  private static final int TEAR_SLICES = 8; // CURATE

  // ---- Color constants --------------------------------------------------------

  // Fallback cool/occult stone and warm-gold, used when the palette swatch is
  // empty. CURATE: picked blind.
  private static final float COOL_H = 255, COOL_S = 55, COOL_B = 62; // violet-indigo stone
  private static final float GOLD_H = 45,  GOLD_S = 85, GOLD_B = 100; // finale gold

  /** Window backing (dim stained-glass field behind the CA tracery). */
  private static final double WINDOW_BACK = 0.10; // CURATE

  /** Tracery brightness boost over the stone brightness. */
  private static final double TRACERY_BOOST = 1.7; // CURATE
  private static final double TRACERY_HUE_OFFSET = 20; // CURATE

  /** Growth below which the empty-valley starfield fades in. */
  private static final double STAR_ONSET = 0.15; // CURATE
  private static final int NUM_STARS = 14; // CURATE
  private static final double STAR_MAX_B = 55; // CURATE

  // ---- Composition helpers ----------------------------------------------------

  private final TriggerBag bag = new TriggerBag("Cathedral");
  private final AudioReactive audio;
  private final TempoLock tempoLock;
  private final Random random = new Random();

  // ---- Parameters (registration order is fixed; do not reorder) ---------------

  public final TriggerParameter seed = bag.register(
    new TriggerParameter("Seed", this::seedTrigger)
    .setDescription("Re-seed the tracery cellular automaton with a fresh random initial row (windows re-generate)"));

  public final TriggerParameter bend = bag.register(
    new TriggerParameter("Bend", this::bendTrigger)
    .setDescription("Dissonance bend: a hue-shift + tear-shear glitch pulse that then heals over ~2 s"));

  public final TriggerParameter heal = bag.register(
    new TriggerParameter("Heal", this::healTrigger)
    .setDescription("Resolution/return: snap the glitch to zero and flood the arches with a completing glow over ~3 s (the 1:43 HEAL callback)"));

  public final TriggerParameter tearDown = bag.register(
    new TriggerParameter("TearDown", this::tearDownTrigger)
    .setDescription("Codex teardown: rotate vertical slices toward their page-edges and back, as if closing a book"));

  public final CompoundParameter energy =
    new CompoundParameter("Energy", 0.35)
    .setDescription("Master energy: ambient (slow growth/CA) to peak (faster growth/CA); never breaks the >= 5 s sustained-motion cap");

  public final CompoundParameter growth =
    new CompoundParameter("Growth", 0.4)
    .setDescription("Swell: how tall/complete the arches are, grown from the floor. Envelope-driven by the arrange composition");

  public final DiscreteParameter rule =
    new DiscreteParameter("Rule", 90, 0, 256)
    .setDescription("Wolfram elementary CA rule number generating the window tracery (90 = Sierpinski by default)");

  public final DiscreteParameter arches =
    new DiscreteParameter("Arches", 3, 1, 7)
    .setDescription("Arches per reference wall; retiled to a whole arcade around each ring so it wraps seamlessly");

  public final CompoundParameter tracery =
    new CompoundParameter("Tracery", 0.6)
    .setDescription("Brightness of the CA-generated window tracery inside the arches");

  public final CompoundParameter glitch =
    new CompoundParameter("Glitch", 0)
    .setDescription("Dissonance amount: hue-shift + horizontal tear-shear of the whole image (Bend pulses this)");

  public final CompoundParameter warmth =
    new CompoundParameter("Warmth", 0)
    .setDescription("Cool/occult (0) to warm-gold (1) color bloom for the finale");

  public final CompoundParameter audioDepth =
    new CompoundParameter("Audio", 0)
    .setDescription("Audio reactivity depth: 0 = pure screensaver (default), 1 = full reactivity");

  public final BooleanParameter sync =
    new BooleanParameter("Sync", true)
    .setDescription("Lock CA generation steps to the tempo grid; OFF (used for this beatless track) free-runs the CA on a timer");

  public final EnumParameter<Tempo.Division> tempoDiv =
    new EnumParameter<Tempo.Division>("TempoDiv", Tempo.Division.QUARTER)
    .setDescription("Tempo division CA generation steps land on when Sync is enabled");

  public final TriggerParameter meta =
    new TriggerParameter("Meta", bag::fire)
    .setDescription("Randomly fire one of Cathedral's triggers or jump a parameter");

  // ---- Surfaces / buffers (all preallocated; zero-alloc render) ---------------

  private final SurfaceCanvas ringCanvas =
    new SurfaceCanvas(Apotheneum.Cube.Ring.LENGTH, Apotheneum.GRID_HEIGHT);       // 200x45
  private final SurfaceCanvas ringWarp =
    new SurfaceCanvas(Apotheneum.Cube.Ring.LENGTH, Apotheneum.GRID_HEIGHT);
  private final SurfaceCanvas cylCanvas =
    new SurfaceCanvas(Apotheneum.Cylinder.Ring.LENGTH, Apotheneum.CYLINDER_HEIGHT); // 120x43
  private final SurfaceCanvas cylWarp =
    new SurfaceCanvas(Apotheneum.Cylinder.Ring.LENGTH, Apotheneum.CYLINDER_HEIGHT);

  /** Tracery CA histories: caHistory[row][col], row 0 = top; new generations
   *  are pushed at the top and flow downward. */
  private final byte[][] cubeCA =
    new byte[Apotheneum.GRID_HEIGHT][Apotheneum.Cube.Ring.LENGTH];
  private final byte[][] cylCA =
    new byte[Apotheneum.CYLINDER_HEIGHT][Apotheneum.Cylinder.Ring.LENGTH];

  // ---- Animation state --------------------------------------------------------

  private double growthShown = 0;   // eased toward growth, rate-capped
  private double glitchPulse = 0;    // Bend envelope 0..1
  private double healGlow = 0;       // Heal envelope 0..1
  private double caAccumMs = 0;      // free-run CA timer

  private boolean tearActive = false;
  private double tearTimeMs = 0;
  private double tearPhase = 0;      // 0 = intact, 1 = fully folded to page-edges

  // Per-frame color cache (computed once in computeColors)
  private int stoneColor = 0xff000000;
  private int traceryColor = 0xff000000;
  private int windowBack = 0xff000000;
  private double glitchEff = 0;

  // Palette swatch cache (Satori-style): recomputed only when the swatch changes
  private int cachedSwatchHash = Integer.MIN_VALUE;
  private float baseCoolH = COOL_H, baseCoolS = COOL_S, baseCoolB = COOL_B;
  private float baseGoldH = GOLD_H, baseGoldS = GOLD_S, baseGoldB = GOLD_B;

  // Empty-valley starfield (normalized positions, slow twinkle)
  private final double[] starX = new double[NUM_STARS];
  private final double[] starY = new double[NUM_STARS];
  private final double[] starPhase = new double[NUM_STARS];
  private final double[] starSpeed = new double[NUM_STARS];
  private final double[] starHue = new double[NUM_STARS];
  private final double[] starDrift = new double[NUM_STARS];

  public Cathedral(LX lx) {
    super(lx);
    this.audio = new AudioReactive(lx).setDepth(this.audioDepth);
    this.tempoLock = new TempoLock(lx);

    addParameter("seed", this.seed);
    addParameter("bend", this.bend);
    addParameter("heal", this.heal);
    addParameter("tearDown", this.tearDown);
    addParameter("energy", this.energy);
    addParameter("growth", this.growth);
    addParameter("rule", this.rule);
    addParameter("arches", this.arches);
    addParameter("tracery", this.tracery);
    addParameter("glitch", this.glitch);
    addParameter("warmth", this.warmth);
    addParameter("audio", this.audioDepth);
    addParameter("sync", this.sync);
    addParameter("tempoDiv", this.tempoDiv);
    addParameter("meta", this.meta);

    // Meta jump candidates — mirrored 1:1 in the Jump candidates table in the .md
    bag.jumpable(this.arches);
    bag.jumpable(this.tracery, 0.3, 0.9);
    bag.jumpable(this.glitch, 0.0, 0.5);   // CURATE: cap; full glitch is a takeover
    bag.jumpable(this.warmth, 0.0, 1.0);
    bag.jumpable(this.growth, 0.2, 1.0);   // CURATE: floor avoids collapsing to the valley

    for (int i = 0; i < NUM_STARS; ++i) {
      this.starX[i] = this.random.nextDouble();
      this.starY[i] = this.random.nextDouble();
      this.starPhase[i] = this.random.nextDouble() * Math.PI * 2;
      this.starSpeed[i] = 0.0006 + this.random.nextDouble() * 0.0010; // rad/ms, slow
      this.starHue[i] = this.random.nextDouble() * 14;                // 0..14: reds
      this.starDrift[i] = (this.random.nextDouble() - 0.5) * 0.00002; // slow parallax
    }

    final int r0 = this.rule.getValuei();
    seedCA(this.cubeCA, Apotheneum.Cube.Ring.LENGTH, r0, false);
    seedCA(this.cylCA, Apotheneum.Cylinder.Ring.LENGTH, r0, false);
  }

  // ---- Triggers ---------------------------------------------------------------

  /** Re-seed both CAs with a fresh RANDOM initial row — the windows regenerate
   *  into a new tracery immediately. Small/medium visible change. */
  private void seedTrigger() {
    final int r0 = this.rule.getValuei();
    seedCA(this.cubeCA, Apotheneum.Cube.Ring.LENGTH, r0, true);
    seedCA(this.cylCA, Apotheneum.Cylinder.Ring.LENGTH, r0, true);
  }

  /** Dissonance bend: arm the glitch pulse (hue-shift + tear-shear), which then
   *  decays back to clean over BEND_MS. Medium change; the resolution matters. */
  private void bendTrigger() {
    this.glitchPulse = 1;
  }

  /** Resolution/return: clear the bend and flood a completing glow. The arches
   *  read as completing and glowing — the HEAL callback. Medium/large change. */
  private void healTrigger() {
    this.glitchPulse = 0;
    this.healGlow = 1;
  }

  /** Codex teardown: rotate vertical slices toward their page-edges and back.
   *  Large change; a full open/close cycle. Ignored while one is running. */
  private void tearDownTrigger() {
    if (!this.tearActive) {
      this.tearActive = true;
      this.tearTimeMs = 0;
      this.tearPhase = 0;
    }
  }

  // ---- Render -----------------------------------------------------------------

  @Override
  protected void render(double deltaMs) {
    this.audio.tick(deltaMs);
    setColors(LXColor.BLACK);

    updateEnvelopes(deltaMs);

    // crossed() must be polled unconditionally every frame to stay current
    final boolean crossed = this.tempoLock.crossed(this.tempoDiv.getEnum());
    boolean stepNow;
    if (this.sync.isOn()) {
      stepNow = crossed;
    } else {
      final double stepMs = Ranges.exp(this.energy.getValue(), CA_STEP_AMBIENT_MS, CA_STEP_PEAK_MS);
      this.caAccumMs += deltaMs;
      stepNow = this.caAccumMs >= stepMs;
      if (stepNow) {
        this.caAccumMs -= stepMs;
      }
    }
    // Treble transients nudge an extra generation for a little shimmer
    if (this.audio.trebleHit()) {
      stepNow = true;
    }
    if (stepNow) {
      final int r = this.rule.getValuei();
      step(this.cubeCA, Apotheneum.Cube.Ring.LENGTH, r);
      step(this.cylCA, Apotheneum.Cylinder.Ring.LENGTH, r);
    }

    computeColors();

    final boolean warp = (this.glitchEff > 0.01) || this.tearActive;

    // Cube ring: the four buttressed walls; interior = the nave
    this.ringCanvas.fill(LXColor.BLACK);
    fillArches(this.ringCanvas, this.cubeCA);
    drawButtresses(this.ringCanvas);
    if (this.growthShown < STAR_ONSET) {
      drawStars(this.ringCanvas);
    }
    if (warp) {
      warpCopy(this.ringCanvas, this.ringWarp);
      this.ringWarp.copyTo(Apotheneum.cube.exterior, this.colors);
    } else {
      this.ringCanvas.copyTo(Apotheneum.cube.exterior, this.colors);
    }
    copyCubeExterior();

    // Cylinder: ambulatory arcade; interior copied
    this.cylCanvas.fill(LXColor.BLACK);
    fillArches(this.cylCanvas, this.cylCA);
    if (this.growthShown < STAR_ONSET) {
      drawStars(this.cylCanvas);
    }
    if (warp) {
      warpCopy(this.cylCanvas, this.cylWarp);
      this.cylWarp.copyTo(Apotheneum.cylinder.exterior, this.colors);
    } else {
      this.cylCanvas.copyTo(Apotheneum.cylinder.exterior, this.colors);
    }
    copyCylinderExterior();
  }

  // ---- Envelopes --------------------------------------------------------------

  private void updateEnvelopes(double deltaMs) {
    // Growth eases toward the knob, rate-capped so a full 0..1 traversal is
    // never faster than GROWTH_SECONDS_PEAK (>= the 5 s sustained cap)
    final double sec = Ranges.lin(this.energy.getValue(), GROWTH_SECONDS_AMBIENT, GROWTH_SECONDS_PEAK);
    final double maxStep = deltaMs / 1000.0 / Math.max(0.001, sec);
    final double target = this.growth.getValue();
    final double diff = target - this.growthShown;
    if (Math.abs(diff) <= maxStep) {
      this.growthShown = target;
    } else {
      this.growthShown += Math.signum(diff) * maxStep;
    }

    this.glitchPulse = Math.max(0, this.glitchPulse - deltaMs / BEND_MS);
    this.healGlow = Math.max(0, this.healGlow - deltaMs / HEAL_MS);

    if (this.tearActive) {
      this.tearTimeMs += deltaMs;
      final double rise = TEAR_RISE_MS;
      final double hold = rise + TEAR_HOLD_MS;
      final double fall = hold + TEAR_FALL_MS;
      if (this.tearTimeMs < rise) {
        this.tearPhase = this.tearTimeMs / rise;
      } else if (this.tearTimeMs < hold) {
        this.tearPhase = 1;
      } else if (this.tearTimeMs < fall) {
        this.tearPhase = 1 - (this.tearTimeMs - hold) / TEAR_FALL_MS;
      } else {
        this.tearActive = false;
        this.tearPhase = 0;
      }
    }

    for (int i = 0; i < NUM_STARS; ++i) {
      this.starPhase[i] += this.starSpeed[i] * deltaMs;
      this.starX[i] += this.starDrift[i] * deltaMs;
      this.starX[i] -= Math.floor(this.starX[i]);
    }
  }

  // ---- Color ------------------------------------------------------------------

  private void computeColors() {
    refreshPaletteCache();

    final double warmthEff = clamp01(this.warmth.getValue() + 0.5 * this.healGlow);
    final double glow = clamp01(0.30 + 0.55 * this.growthShown
      + 0.30 * this.audio.level + 0.5 * this.healGlow);
    this.glitchEff = clamp01(this.glitch.getValue() + this.glitchPulse);
    final double glitchHue = this.glitchEff * GLITCH_HUE_DEG;

    final float h = (float) (wrapLerpHue(this.baseCoolH, this.baseGoldH, warmthEff) + glitchHue);
    final float s = (float) lerp(this.baseCoolS, this.baseGoldS, warmthEff);
    final float b = (float) (lerp(this.baseCoolB, this.baseGoldB, warmthEff) * glow);

    this.stoneColor = LXColor.hsb(wrap360(h), s, clampB(b));
    this.windowBack = LXColor.hsb(wrap360(h), s, clampB((float) (b * WINDOW_BACK)));

    final double traceryB = b * TRACERY_BOOST * this.tracery.getValue()
      * (1.0 + 0.4 * this.audio.treble);
    this.traceryColor = LXColor.hsb(
      wrap360((float) (h + TRACERY_HUE_OFFSET)),
      clampB((float) (s + 10)),
      clampB((float) traceryB));
  }

  private void refreshPaletteCache() {
    final List<LXDynamicColor> swatch = this.lx.engine.palette.swatch.colors;
    final int n = swatch.size();
    int hash = n;
    if (n > 0) {
      hash = 31 * hash + swatch.get(0).getColor();
      hash = 31 * hash + swatch.get(n - 1).getColor();
    }
    if (hash == this.cachedSwatchHash) {
      return;
    }
    this.cachedSwatchHash = hash;
    if (n == 0) {
      this.baseCoolH = COOL_H; this.baseCoolS = COOL_S; this.baseCoolB = COOL_B;
      this.baseGoldH = GOLD_H; this.baseGoldS = GOLD_S; this.baseGoldB = GOLD_B;
      return;
    }
    // Cool end = first swatch color; warm end = last swatch color
    final int cool = swatch.get(0).getColor();
    final int gold = swatch.get(n - 1).getColor();
    this.baseCoolH = LXColor.h(cool); this.baseCoolS = LXColor.s(cool); this.baseCoolB = LXColor.b(cool);
    this.baseGoldH = LXColor.h(gold); this.baseGoldS = LXColor.s(gold); this.baseGoldB = LXColor.b(gold);
  }

  // ---- Arch rendering ---------------------------------------------------------

  private void fillArches(SurfaceCanvas c, byte[][] ca) {
    final int w = c.width;
    final int h = c.height;
    final double g = this.growthShown;
    if (g <= 0.001) {
      return; // nothing grown yet (valley); stars handle the field
    }
    final int nArches = this.arches.getValuei();
    // Whole number of arches around the full ring for a seamless wrap
    final int nRing = Math.max(1, (int) Math.round(w * nArches / REF_WALL_COLS));
    final double archWf = (double) w / nRing;

    final double springH = g * SPRING_FRAC * (h - 1);
    final double apexH = g * APEX_FRAC * (h - 1);

    for (int x = 0; x < w; ++x) {
      final double posf = x / archWf;
      final int ai = (int) Math.floor(posf);
      final double local = posf - ai;              // 0..1 within the arch
      final double centerDist = Math.abs(local - 0.5);
      final double norm = centerDist * 2;          // 0 center, 1 edges
      final double shape = Math.pow(Math.max(0, 1 - norm), ARCH_EXP);
      final double topH = springH + (apexH - springH) * shape;

      for (int y = 0; y < h; ++y) {
        final double hb = (h - 1) - y;             // height from the floor
        if (hb < 0 || hb > topH) {
          continue;                                 // outside the silhouette
        }
        final boolean pier = (norm > PIER_NORM) && (hb <= springH);
        final boolean mullion = (centerDist < MULLION_HALF) && (hb <= springH);
        final boolean base = hb < BASE_ROWS;
        final boolean outline = (topH - hb) < RIB_ROWS;
        if (pier || mullion || base || outline) {
          c.set(x, y, this.stoneColor);
        } else if (ca[y][x] != 0) {
          c.set(x, y, this.traceryColor);           // CA-generated tracery
        } else {
          c.set(x, y, this.windowBack);             // dim stained-glass field
        }
      }
    }
  }

  /** Flying buttresses: short diagonal stone struts that lean off each arch
   *  boundary, fading in as growth passes BUTTRESS_ONSET. Cube ring only look;
   *  drawn for every surface passed (cylinder skips via its own call site).
   *  CURATE: strut geometry is a first-pass approximation. */
  private void drawButtresses(SurfaceCanvas c) {
    final double g = this.growthShown;
    if (g < BUTTRESS_ONSET) {
      return;
    }
    final double bf = clamp01((g - BUTTRESS_ONSET) / (1 - BUTTRESS_ONSET));
    final int w = c.width;
    final int h = c.height;
    final int nArches = this.arches.getValuei();
    final int nRing = Math.max(1, (int) Math.round(w * nArches / REF_WALL_COLS));
    final double archWf = (double) w / nRing;
    final int strutColor = scale(this.stoneColor, 0.65 + 0.35 * bf);

    final int springY = (int) Math.round((h - 1) - g * SPRING_FRAC * (h - 1));
    final int dx = (int) Math.round(6 * bf);       // CURATE: strut reach
    final int drop = (int) Math.round(8 * bf);     // CURATE: strut drop
    if (dx <= 0 || drop <= 0) {
      return;
    }
    for (int a = 0; a < nRing; ++a) {
      final int bx = (int) Math.round(a * archWf);
      // Two struts leaning outward from the pier top toward the floor
      c.line(bx, springY, bx - dx, Math.min(h - 1, springY + drop), strutColor);
      c.line(bx, springY, bx + dx, Math.min(h - 1, springY + drop), strutColor);
    }
  }

  // ---- Empty-valley starfield -------------------------------------------------

  private void drawStars(SurfaceCanvas c) {
    final double alpha = clamp01((STAR_ONSET - this.growthShown) / STAR_ONSET);
    if (alpha <= 0.01) {
      return;
    }
    final int w = c.width;
    final int h = c.height;
    for (int i = 0; i < NUM_STARS; ++i) {
      final double tw = 0.4 + 0.6 * (0.5 + 0.5 * Math.sin(this.starPhase[i]));
      final float b = clampB((float) (STAR_MAX_B * alpha * tw));
      if (b < 1) {
        continue;
      }
      final int x = (int) Math.floor(this.starX[i] * w);
      final int y = (int) Math.floor(this.starY[i] * h);
      c.setMax(x, y, LXColor.hsb((float) this.starHue[i], 85, b));
    }
  }

  // ---- Glitch / codex warp ----------------------------------------------------

  /** Copy src -> dst applying the tear-shear glitch (per-row horizontal offset)
   *  and the codex teardown (per-slice horizontal compression toward the slice's
   *  left page-edge). Identity when neither is active. x wraps (ring topology).*/
  private void warpCopy(SurfaceCanvas src, SurfaceCanvas dst) {
    final int w = src.width;
    final int h = src.height;
    final int sliceW = Math.max(1, w / TEAR_SLICES);
    final double tp = this.tearPhase;
    final double gEff = this.glitchEff;

    for (int y = 0; y < h; ++y) {
      final int shear = (gEff > 0.01) ? (int) Math.round(shearNoise(y) * MAX_SHEAR * gEff) : 0;
      for (int x = 0; x < w; ++x) {
        int srcX = x;
        if (tp > 0) {
          final int slice = x / sliceW;
          final int sliceStart = slice * sliceW;
          // Earlier slices lead so the fold sweeps across (staggered)
          final double lt = clamp01((tp - (slice / (double) TEAR_SLICES) * 0.5) / 0.5);
          final double comp = 1 - lt;               // remaining width fraction
          if (comp <= 0.02) {
            dst.set(x, y, 0xff000000);              // slice folded to its edge
            continue;
          }
          final double rel = (x - sliceStart) / comp;
          if (rel >= sliceW) {
            dst.set(x, y, 0xff000000);              // beyond the folded page
            continue;
          }
          srcX = sliceStart + (int) rel;
        }
        dst.set(x, y, src.get(srcX + shear, y));    // get() wraps x
      }
    }
  }

  /** Cheap deterministic per-row shear noise in [-1, 1]. */
  private static double shearNoise(int y) {
    double n = Math.sin(y * 12.9898) * 43758.5453;
    n -= Math.floor(n);
    return n * 2 - 1;
  }

  // ---- Cellular automaton -----------------------------------------------------

  /** Seed a CA history: top row from a single center cell (or a random sparse
   *  row) then generate downward to fill the window. */
  private void seedCA(byte[][] hist, int w, int rule, boolean randomize) {
    final byte[] top = hist[0];
    java.util.Arrays.fill(top, (byte) 0);
    if (randomize) {
      for (int i = 0; i < w; ++i) {
        top[i] = (byte) (this.random.nextInt(4) == 0 ? 1 : 0); // ~25% density
      }
    } else {
      top[w / 2] = 1;
    }
    for (int r = 1; r < hist.length; ++r) {
      evolve(hist[r - 1], hist[r], w, rule);
    }
  }

  /** Advance the CA one generation: push a new top row (evolved from the old
   *  top) and flow the rest downward. Zero-alloc (pointer rotation). */
  private static void step(byte[][] hist, int w, int rule) {
    final byte[] recycled = hist[hist.length - 1];
    for (int r = hist.length - 1; r >= 1; --r) {
      hist[r] = hist[r - 1];
    }
    hist[0] = recycled;
    evolve(hist[1], hist[0], w, rule);
  }

  /** Elementary CA update: out[i] = bit (3-neighborhood -> rule). Wraps (ring).*/
  private static void evolve(byte[] in, byte[] out, int w, int rule) {
    for (int i = 0; i < w; ++i) {
      final int l = in[(i - 1 + w) % w];
      final int cc = in[i];
      final int r = in[(i + 1) % w];
      final int idx = (l << 2) | (cc << 1) | r;
      out[i] = (byte) ((rule >> idx) & 1);
    }
  }

  // ---- Small math helpers -----------------------------------------------------

  private static double clamp01(double v) {
    return (v < 0) ? 0 : (v > 1) ? 1 : v;
  }

  private static float clampB(float v) {
    return (v < 0) ? 0 : (v > 100) ? 100 : v;
  }

  private static double lerp(double a, double b, double t) {
    return a + (b - a) * t;
  }

  /** Shortest-path hue interpolation in degrees (wraps around the color wheel).*/
  private static double wrapLerpHue(double a, double b, double t) {
    double d = b - a;
    d -= 360 * Math.floor((d + 180) / 360);
    return a + d * t;
  }

  private static float wrap360(float h) {
    h -= 360f * (float) Math.floor(h / 360f);
    return h;
  }

  private static int scale(int argb, double m) {
    if (m <= 0) {
      return 0xff000000;
    }
    if (m > 1) {
      m = 1;
    }
    final int r = (int) (((argb >> 16) & 0xff) * m);
    final int g = (int) (((argb >> 8) & 0xff) * m);
    final int b = (int) ((argb & 0xff) * m);
    return 0xff000000 | (r << 16) | (g << 8) | b;
  }
}
